% Run all unit tests for all model variants of the exoskeleton
% The unit test framework is generated by the model generation toolbox from
% https://github.com/SchapplM/robsynth-modelgen

% Moritz Schappler, schappler@imes.uni-hannover.de, 2020-06
% (C) Institut für Mechatronische Systeme, Leibniz Universität Hannover

clear
clc
for i = 1:8
  % initialize current path. Gets clear from called scripts
  this_path = fileparts( which('toolbox_testsuite.m') );
  switch i
    case 1
      ts = fullfile('KAS5m3','testfcn','KAS5m3_test_everything_fixbase_kinematics.m');
    case 2
      ts = fullfile('KAS5m5OL','testfcn','KAS5m5OL_test_everything_fixbase_kinematics.m');
    case 3
      ts = fullfile('KAS5m5','testfcn','KAS5m5_test_everything_fixbase_kinematics.m');
    case 4
      ts = fullfile('KAS5m7DE1','testfcn','KAS5m7DE1_test_everything_fixbase.m');
    case 5
      ts = fullfile('KAS5m7DE2','testfcn','KAS5m7DE2_test_everything_fixbase.m');
    case 6
      ts = fullfile('KAS5m7TE','testfcn','KAS5m7TE_test_everything_fixbase.m');
    case 7
      ts = fullfile('KAS5m7OL','testfcn','KAS5m7OL_test_everything_fixbase.m');
    case 8
      ts = fullfile('KAS5m7IC','testfcn','KAS5m7IC_test_everything.m');
  end
  % Run the test suite for this model of the exoskeleton
  run(fullfile(this_path, ts));
end
  